# -*- coding: utf-8 -*-
"""
This family file was auto-generated by $Id: generate_family_file.py 11542 2013-05-17 19:58:40Z drtrigon $
Configuration parameters:
  url = http://dokuwiki.wikivote.ru/index.php/Main_Page
  name = dokuwiki

Please do not commit this to the SVN repository!
"""

import family

class Family(family.Family):
    def __init__(self):
        family.Family.__init__(self)
        self.name = 'dokuwiki'
        self.langs = {
            'en': u'dokuwiki.wikivote.ru',
        }

        self.namespaces[4] = self.namespaces.get(4, {})
        self.namespaces[4][u'en'] = [u'Testfutur']
        self.namespaces[5] = self.namespaces.get(5, {})
        self.namespaces[5][u'en'] = [u'Testfutur talk']
        self.namespaces[6] = self.namespaces.get(6, {})
        self.namespaces[6][u'en'] = [u'Image']
        self.namespaces[7] = self.namespaces.get(7, {})
        self.namespaces[7][u'en'] = [u'Image talk']


    def scriptpath(self, code):
        return {
            'en': u'',
        }[code]

    def version(self, code):
        return {
            'en': u'1.22.0',
        }[code]
