# -*- coding: utf-8 -*-
"""
This family file was auto-generated by $Id: generate_family_file.py 11542 2013-05-17 19:58:40Z drtrigon $
Configuration parameters:
  url = http://en.wikioffuture.org/Special:BrowseData
  name = wikioffuture

Please do not commit this to the SVN repository!
"""

import family

class Family(family.Family):
    def __init__(self):
        family.Family.__init__(self)
        self.name = 'wikioffuture'
        self.langs = {
            'en': u'en.wikioffuture.org',
        }

        self.namespaces[107] = self.namespaces.get(107, {})
        self.namespaces[107][u'en'] = [u'Form talk']
        self.namespaces[4] = self.namespaces.get(4, {})
        self.namespaces[4][u'en'] = [u'Wiki of Future']
        self.namespaces[5] = self.namespaces.get(5, {})
        self.namespaces[5][u'en'] = [u'Wiki of Future talk']
        self.namespaces[102] = self.namespaces.get(102, {})
        self.namespaces[102][u'en'] = [u'Property']
        self.namespaces[103] = self.namespaces.get(103, {})
        self.namespaces[103][u'en'] = [u'Property talk']
        self.namespaces[170] = self.namespaces.get(170, {})
        self.namespaces[170][u'en'] = [u'Filter']
        self.namespaces[171] = self.namespaces.get(171, {})
        self.namespaces[171][u'en'] = [u'Filter talk']
        self.namespaces[108] = self.namespaces.get(108, {})
        self.namespaces[108][u'en'] = [u'Concept']
        self.namespaces[109] = self.namespaces.get(109, {})
        self.namespaces[109][u'en'] = [u'Concept talk']
        self.namespaces[7] = self.namespaces.get(7, {})
        self.namespaces[7][u'en'] = [u'Image talk']
        self.namespaces[420] = self.namespaces.get(420, {})
        self.namespaces[420][u'en'] = [u'Layer']
        self.namespaces[6] = self.namespaces.get(6, {})
        self.namespaces[6][u'en'] = [u'Image']
        self.namespaces[106] = self.namespaces.get(106, {})
        self.namespaces[106][u'en'] = [u'Form']
        self.namespaces[421] = self.namespaces.get(421, {})
        self.namespaces[421][u'en'] = [u'Layer talk']


    def scriptpath(self, code):
        return {
            'en': u'/w',
        }[code]

    def version(self, code):
        return {
            'en': u'1.20.4',
        }[code]
